# Diamond-Analysis-3

The goal in this step is to integrate additional diamond data feeds and re-evaluate (1) our model and (2) the data source set for real world diamond estimation

In [60]:
import pandas as pd
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.utils import shuffle

diamonds = pd.read_csv('diamonds-1a.csv')
diamonds = shuffle(diamonds, random_state=0)   # is this a repeatable shuffle by defautl w/o param
diamonds.head()
diamonds.describe()

# Split the targets into training/testing sets
diamonds_y_train = diamonds.price[:-20]
diamonds_y_test = diamonds.price[-20:]
diamonds = diamonds.drop(columns=['price','Unnamed: 0'])

# Split the data into training/testing sets
diamonds_X_train = diamonds[:-20]
diamonds_X_test = diamonds[-20:]

# Create linear regression object
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(diamonds_X_train, diamonds_y_train)

print('Score: ', regr.score(diamonds_X_test, diamonds_y_test))
print(regr.coef_)

Score:  0.9760420391678098
[8.89120958e+03 2.19392780e+16 2.19392780e+16 2.19392780e+16
 2.19392780e+16 2.19392780e+16 4.18666049e+15 4.18666049e+15
 4.18666049e+15 4.18666049e+15 4.18666049e+15 4.18666049e+15
 4.18666049e+15 1.59621301e+15 1.59621301e+15 1.59621301e+15
 1.59621301e+15 1.59621301e+15 1.59621301e+15 1.59621301e+15
 1.59621301e+15]

In [55]:
# loading important libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
 
# Loading the data
DATA_DIR = '.'
FILE_NAME = 'Diamond_source2.csv'
data_path = os.path.join(DATA_DIR, FILE_NAME)
diamonds2 = pd.read_csv(data_path)

# col cleanup
diamonds2 = diamonds2.drop(columns=['Unnamed: 0'])
colors = pd.get_dummies( diamonds2['colour'], prefix='color_')
clarity = pd.get_dummies( diamonds2['clarity'], prefix='clarity_')
price = diamonds2['price']
diamonds2 = diamonds2.join(colors).join(clarity)
diamonds2 = diamonds2.drop(columns=['price','colour','clarity','certification'])

# zero filling the extra cols
diamonds2.insert(1,'cut__Very Good',0)
diamonds2.insert(1,'cut__Premium',0)
diamonds2.insert(1,'cut__Ideal',0)
diamonds2.insert(1,'cut__Good',0)
diamonds2.insert(1,'cut__Fair',0)
diamonds2.insert(12,'color__J',0)
diamonds2.insert(13,'clarity__I1',0)
diamonds2.insert(15,'clarity__SI2',0)
diamonds2.insert(15,'clarity__SI1',0)
diamonds2.head()

diamonds_y_pred = regr.predict(diamonds2)
res = pd.DataFrame(diamonds_y_pred)
res['actual'] = price

print('Score: ', regr.score(diamonds2, price))
res.head()

Score:  -4.169688084737268e+25

              0  actual
0 -2.193928e+16    1302
1 -2.193928e+16    1510
2 -2.193928e+16    1510
3 -2.193928e+16    1260
4 -2.193928e+16    1641

In [27]:
diamonds.head()

,carat,cut__Fair,cut__Good,cut__Ideal,cut__Premium,cut__Very Good,color__D,color__E,color__F,color__G,...,color__I,color__J,clarity__I1,clarity__IF,clarity__SI1,clarity__SI2,clarity__VS1,clarity__VS2,clarity__VVS1,clarity__VVS2
15840,1.02,0,0,1,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
33198,0.40,0,0,0,1,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
19618,1.51,0,1,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
27089,2.10,0,0,1,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
28921,0.30,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [58]:
diamonds2.head()

,carat,cut__Fair,cut__Good,cut__Ideal,cut__Premium,cut__Very Good,color__D,color__E,color__F,color__G,...,color__I,color__J,clarity__I1,clarity__IF,clarity__SI1,clarity__SI2,clarity__VS1,clarity__VS2,clarity__VVS1,clarity__VVS2
0,0.30,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0.30,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
2,0.30,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,0
3,0.30,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,0
4,0.31,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0